### ISSUE TITLE
Información sobre la vista

### ISSUE THREAD

**Issue by eacha** [niclabs/AdkintunMobile-AndroidClient#102]
En la información de la vista es posible clickear los botones en la burbuja transparente, esto permite clickear nuevamente el botón de información creando nuevamente esta vista, si esto se realiza varias veces la aplicación se cae.

Adjunto imagen de este caso
![photo603077296453167051](https://cloud.githubusercontent.com/assets/5059451/16958707/a9e368f2-4daf-11e6-8f5e-b0aa2ef77675.jpg)

**Comment by dmadariaga** [comment]
cerrado en #109
