### ISSUE TITLE
Primer inicio

### ISSUE THREAD

**Issue by eacha** [niclabs/adkintunmobile-androidclient#104]
En el primer uso de la aplicación, la información de las vistas aparece en un momento aleatorio y no cuando parte la aplicación. En la información de las vistas la primera vez no hay datos graficados, por lo que no es muy útil la explicación en ese momento, sugiero agregar datos falsos para demostrar la funcionalidad.

**Comment by sebablasko** [comment]
Se implementó el sistema de tutoriales para explicar la información mostrada en cada vista, llamable cuando el usuario lo desee, así, cuando si hay datos, se puede volver a mostrar
