### ISSUE TITLE
ApplicationsTrafficActivity.java line 245

### ISSUE THREAD

**Issue by sebablasko** [niclabs/AdkintunMobile-AndroidClient#108]
#### in cl.niclabs.adkintunmobile.views.applicationstraffic.ApplicationsTrafficActivity$2.onClick

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/niclabs/android/apps/cl.niclabs.adkintunmobile/issues/578e9051ffcdc0425003b6b3](https://fabric.io/niclabs/android/apps/cl.niclabs.adkintunmobile/issues/578e9051ffcdc0425003b6b3)

**Comment by dmadariaga** [comment]
cerrado en #109
