### ISSUE TITLE
GraphView.java line 286

### ISSUE THREAD

**Issue by sebablasko** [niclabs/adkintunmobile-androidclient#154]
#### in com.jjoe64.graphview.GraphView.drawGraphElements

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/niclabs/android/apps/cl.niclabs.adkintunmobile/issues/586c81970aeb16625bbc0dda](https://fabric.io/niclabs/android/apps/cl.niclabs.adkintunmobile/issues/586c81970aeb16625bbc0dda)

**Comment by madestro** [comment]
update fabric! @dmadariaga must be the new owner of these kind of messages

**Comment by dmadariaga** [comment]
done (#156)
