### ISSUE TITLE
Mediciones de intensidad de señal incorrectas

### ISSUE THREAD

**Issue by fquintan** [niclabs/adkintunmobile-androidclient#174]
En el servidor hay mediciones de intensidad de señal obviamente incorrectas (> 10^7 dbm). 
Actualmente se están filtrando en el servidor, pero debería ser responsabilidad del cliente revisar estos datos antes de enviarlos.

**Comment by fquintan** [comment]
Propongo que antes de guardar un evento el cliente revise si la medición en dbm es menor a cero. En la base de datos los valores pasan violentamente de 0  a > 1000.

**Comment by madestro** [comment]
verificaron el porqué se escriben esos valores?

**Comment by fquintan** [comment]
No hemos podido reproducirlo, pero viendo el código esos valores vienen directo del sistema operativo. [En este archivo](https://github.com/niclabs/adkintun-mobile-middleware/blob/master/library/src/main/java/cl/niclabs/adkmobile/monitor/Telephony.java) línea ~300 se ve que existe el mismo problema para el cálculo de error de la medición, en ese caso revisan que los valores entregados estén en el rango correcto según la documentación, sino botan la medición. Creo que se debería hacer lo mismo en este caso.

**Comment by fquintan** [comment]
Según la [documentación](https://developer.android.com/reference/android/telephony/SignalStrength.html#getGsmSignalStrength()) el valor de getGsmSignalStrength debería estar entre 0 y 31
